language: node_js
node_js: lts/*
git:
  depth: 1
cache:
  directories:
    - node_modules
    - ${HOME}/google-cloud-sdk/
stages:
  - test
  - name: docs
    if: branch = master
before_script:
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: docs
      env:
        - SECRET=.travis-key SOURCE=docs-compiled CLOUDSDK_CORE_DISABLE_PROMPTS=1
      script: skip
      after_success:
        - |
          gcloud version || true
          if [ ! -d "${HOME}/google-cloud-sdk/bin" ]; then rm -rf ${HOME}/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
          ${HOME}/google-cloud-sdk/install.sh -q
          source ${HOME}/google-cloud-sdk/path.bash.inc
          openssl aes-256-cbc -K $encrypted_304dd3daa2bc_key -iv $encrypted_304dd3daa2bc_iv -in ${SECRET}.enc -out ${SECRET} -d
          gcloud auth activate-service-account --key-file ${SECRET}
          rm ${SECRET}
          npm run docs
          gsutil -m cp -ra public-read "${SOURCE}/**" "gs://${BUCKET}/"

