export const UNSPECIFIED_ERROR = 'UNSPECIFIED_ERROR'

export const MALFORMED_PACKET = 'MALFORMED_PACKET'

export const PROTOCOL_ERROR = 'PROTOCOL_ERROR'

export const IMPLEMENTATION_SPECIFIC_ERROR = 'IMPLEMENTATION_SPECIFIC_ERROR'

export const UNSUPPORTED_PROTOCOL_VERSION = 'UNSUPPORTED_PROTOCOL_VERSION'

export const CLIENT_IDENTIFIER_NOT_VALID = 'CLIENT_IDENTIFIER_NOT_VALID'

export const BAD_USERNAME_OR_PASSWORD = 'BAD_USERNAME_OR_PASSWORD'

export const NOT_AUTHORIZED = 'NOT_AUTHORIZED'

export const SERVER_UNAVAILABLE = 'SERVER_UNAVAILABLE'

export const SERVER_BUSY = 'SERVER_BUSY'

export const BANNED = 'BANNED'

export const SERVER_SHUTTING_DOWN = 'SERVER_SHUTTING_DOWN'

export const BAD_AUTHENTICATION_METHOD = 'BAD_AUTHENTICATION_METHOD'

export const KEEP_ALIVE_TIMEOUT = 'KEEP_ALIVE_TIMEOUT'

export const SESSION_TAKEN_OVER = 'SESSION_TAKEN_OVER'

export const mqttReasonCodeNameEnum = {
  128: UNSPECIFIED_ERROR,
  129: MALFORMED_PACKET,
  130: PROTOCOL_ERROR,
  131: IMPLEMENTATION_SPECIFIC_ERROR,
  132: UNSUPPORTED_PROTOCOL_VERSION,
  133: CLIENT_IDENTIFIER_NOT_VALID,
  134: BAD_USERNAME_OR_PASSWORD,
  135: NOT_AUTHORIZED,
  136: SERVER_UNAVAILABLE,
  137: SERVER_BUSY,
  138: BANNED,
  139: SERVER_SHUTTING_DOWN,
  140: BAD_AUTHENTICATION_METHOD,
  141: KEEP_ALIVE_TIMEOUT,
  142: SESSION_TAKEN_OVER
}

export const mqttErrors = [
  UNSPECIFIED_ERROR,
  MALFORMED_PACKET,
  PROTOCOL_ERROR,
  IMPLEMENTATION_SPECIFIC_ERROR,
  UNSUPPORTED_PROTOCOL_VERSION,
  CLIENT_IDENTIFIER_NOT_VALID,
  BAD_USERNAME_OR_PASSWORD,
  NOT_AUTHORIZED,
  SERVER_UNAVAILABLE,
  SERVER_BUSY,
  BANNED,
  SERVER_SHUTTING_DOWN,
  BAD_AUTHENTICATION_METHOD,
  KEEP_ALIVE_TIMEOUT,
  SESSION_TAKEN_OVER
]

export const mqttAppErrors = [CLIENT_IDENTIFIER_NOT_VALID, BAD_USERNAME_OR_PASSWORD, NOT_AUTHORIZED]

export const mqttServerErrors = [
  UNSPECIFIED_ERROR,
  MALFORMED_PACKET,
  PROTOCOL_ERROR,
  IMPLEMENTATION_SPECIFIC_ERROR,
  UNSUPPORTED_PROTOCOL_VERSION,
  SERVER_UNAVAILABLE,
  SERVER_BUSY,
  BANNED,
  SERVER_SHUTTING_DOWN,
  BAD_AUTHENTICATION_METHOD
]

export const mqttUserErrors = [SESSION_TAKEN_OVER]
